version: '2'
services:
    fmsapp-app:
        image: fmsapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://fmsapp-mariadb:3306/fmsapp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    fmsapp-mariadb:
        extends:
            file: mariadb.yml
            service: fmsapp-mariadb
